server:
  port: 8088


spring:
  application:
    name: ums-service
    profiles:
      active: dev
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/wincidb?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.example.mybatis.cache.dao.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
